name: Blog Workflow

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Apply Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://zachjmurphy.ca/feed.xml
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          committer_username: GitHub Actions
